
### primary goals: 
 ### update indexer agent component to enable syncing on all chains without extra work
 ### enable collection of query fees on arbitrum 
 
### secondary goals: 
 ### can bk get access to the indexer-agent sql database to run some queries on QoS? 
 ### cost models: validate with orjan bk can do this in allocation mgmt
 ### bk would like to setup qos metrics in grafana (not also know where this connects to)
 ### do we want to add a graphcast (subgraph radio) container? would help with presyncing
  ### https://docs.graphops.xyz/graphcast/intro + https://github.com/graphops/graphcast-sdk
 

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: indexer-agent
spec:
  serviceName: indexer-agent
  replicas: 1
  selector:
    matchLabels:
      app: indexer-agent
  template:
    metadata:
      annotations:
        prometheus.io/port: metrics
      labels:
        app: indexer-agent
    spec:
      nodeSelector:
        kubernetes.io/hostname: agent-2
      containers:
        - name: indexer-agent
          image: ghcr.io/graphprotocol/indexer-agent:v0.20.12
          command: ["node", "/opt/indexer/packages/indexer-agent/dist/index.js", "start"]
          args:
            - --poi-dispute-monitoring=true
            - --poi-disputable-epochs=100
            - --epoch-subgraph-endpoint=https://api.thegraph.com/subgraphs/name/graphprotocol/mainnet-epoch-block-oracle
          ports:
            - name: metrics
              containerPort: 7300
            - name: http
              containerPort: 7600
            - name: management
              containerPort: 8000
            - name: syncing
              containerPort: 8001
          env:
            - name: INDEXER_AGENT_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: operator-mnemonic
                  key: words
                  
            ### Updated Jan 06 2024
            
            - name: INDEXER_AGENT_INDEXER_ADDRESS
              value: "0x920fdeb00ee04dd72f62d8a8f80f13c82ef76c1e"
            - name: INDEXER_AGENT_INDEX_NODE_IDS
              value: "index_node_0"
            - name: INDEXER_AGENT_INJECT_DAI
              value: "true"
            - name: INDEXER_AGENT_REBATE_CLAIM_TRESHOLD
              value: "30"
            - name: INDEXER_AGENT_REBATE_CLAIM_BATCH_THRESHOLD
              value: "200"
            - name: INDEXER_AGENT_REBATE_CLAIM_MAX_BATCH_SIZE
              value: "100"
            - name: INDEXER_AGENT_VOUCHER_REDEMPTION_THRESHOLD
              value: "30"
            - name: INDEXER_AGENT_VOUCHER_REDEMPTION_BATCH_THRESHOLD
              value: "200"
            - name: INDEXER_AGENT_VOUCHER_REDEMPTION_MAX_BATCH_SIZE
              value: "100"
            - name: INDEXER_AGENT_ALLOCATION_MANAGEMENT
              value: "manual"
            - name: INDEXER_AGENT_ETHEREUM_NETWORK
              value: mainnet
            - name: INDEXER_AGENT_ETHEREUM
              # value: http://erigon-eth-mainnet-rpc:8546
              # need to update, are we really using alchemy for this? 
              value: https://eth-mainnet.g.alchemy.com/v2/QVIJotCYnzNRzDT6HRCJ0gfqzHwqgSxi
            - name: INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT
              value: http://query-node-public:9000
            - name: INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT
              value: http://index-node:8030/graphql
            - name: INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT
              value: http://index-node:8020
            - name: INDEXER_AGENT_PUBLIC_INDEXER_URL
              value: https://index.braindexer.io/
            - name: INDEXER_AGENT_INDEXER_GEO_COORDINATES
              value: -60.16952 24.93545
            - name: INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT
              value: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet
            # - name: INDEXER_AGENT_NETWORK_SUBGRAPH_DEPLOYMENT
              # value: as
            - name: INDEXER_AGENT_POSTGRES_HOST
              value: postgres-indexer
            - name: INDEXER_AGENT_POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-indexer-config
                  key: postgres_user
            - name: INDEXER_AGENT_POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-indexer-config
                  key: postgres_db
            - name: INDEXER_AGENT_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-indexer-config
                  key: postgres_pass
            - name: INDEXER_AGENT_DAI_CONTRACT
              value: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
            - name: INDEXER_AGENT_COLLECT_RECEIPTS_ENDPOINT
              value: https://gateway.network.thegraph.com/collect-receipts
            # - name: INDEXER_AGENT_OFFCHAIN_SUBGRAPHS
              # value: asdasd
            - name: INDEXER_AGENT_GAS_PRICE_MAX
              value: "100"