---
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())

library("tidyverse")
library("lubridate")
library("magick")
```

```{r warning=FALSE, message=FALSE}
query_subgraph = function(api_or_query_key, endpoint, graphql_query){
  
  library("ghql")
  library("jsonlite")
  
  graphql_conn <- ghql::GraphqlClient$new(
    url = endpoint, 
    headers = list(Authorization = paste0("Bearer ", api_or_query_key)))
  
  qry <- Query$new()
  qry$query('query_table', graphql_query)
  query_table <- graphql_conn$exec(qry$queries$query_table)
  query_table <- jsonlite::fromJSON(query_table)
  query_table <- query_table$data
  query_table
}

unix_today = as.numeric(as.POSIXct(today(), format="%Y-%m-%d"))
date_before = (as.Date(today(), format="%d/%m/%Y") - 1)
unix_before = as.numeric(as.POSIXct(date_before, format="%Y-%m-%d"))

my_query_key = "pWRuYW1lTnRlc3QtcXVlcnkta2V5ZHVzZXJUTesSNU6pKVj6EfyMEkqfErYbirRmc2lnbmVyVE3rEjVOqSlY-hH8jBJKnxK2G4q0aGNoYWluX2lkGaSxaGNvbnRyYWN0VEgvWNNRPjhgNmcEBLNcs_LfZ6dQxQnqFbv8C1tHjhKNtXPDWEvMUYUrfuDUJTFT9JxA7ik7EzT15sBfazw6dbYo9kM6PS3AE86idfR8G7nKfnhMRhs"
qos_oracle = "https://api.thegraph.com/subgraphs/name/juanmardefago/gateway-qos-oracle"
network_subgraph = "https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-arbitrum"

top_subgraphs_by_query_volume = str_c('{
  queryDailyDataPoints(
    first: 1000
    where: {
      gateway_id: "mainnet-arbitrum", 
      chain_id: "mainnet", 
      dayStart_gt: "',unix_before,'"} 
    orderBy: query_count
    orderDirection: desc
  ) {
    subgraphDeployment {
      id
    }
    query_count
    gateway_query_success_rate 
    avg_gateway_latency_ms
    gateway_id
    chain_id
    dayStart
  }
}')

subgraphs_metadata_query = str_c('{
  subgraphs(first: 1000, where: {active: true}) {
    metadata {
      displayName
    }
    currentVersion {
      subgraphDeployment {
        manifest {
          id
          network
        }
      }
    }
  }
}')


top_subgraphs = query_subgraph(my_query_key, qos_oracle, top_subgraphs_by_query_volume)
top_subgraphs = as.data.frame(top_subgraphs$queryDailyDataPoints) %>% 
  unnest(subgraphDeployment) %>% 
  mutate(query_count = as.numeric(query_count)) %>% 
  rename(deployment_id = id) %>% 
  filter(!is.na(deployment_id))

# clean subgraph data 
subgraphs_metadata = query_subgraph(my_query_key, network_subgraph, subgraphs_metadata_query)
subgraphs_metadata = subgraphs_metadata$subgraphs 
for (var in list("metadata", "currentVersion", "subgraphDeployment", "manifest")){
  subgraphs_metadata = unnest_longer(subgraphs_metadata, 
                                     var, indices_include = FALSE) %>% unnest(var)
}

subgraphs_metadata = subgraphs_metadata %>% 
  rename(display_name = displayName,
         deployment_id = id) %>% 
  filter(!is.na(display_name)) 

subgraphs_data = top_subgraphs %>% 
  left_join(subgraphs_metadata, by = "deployment_id") %>% 
  select(display_name, everything(), -network) %>% 
  rename(success_rate = gateway_query_success_rate,
         avg_latency = avg_gateway_latency_ms) %>% 
  mutate(success_rate = as.numeric(success_rate),
         avg_latency = as.numeric(avg_latency))

subgraphs_data %>% 
  select(display_name, query_count, success_rate, avg_latency, deployment_id) 

subgraphs_data %>% 
  select(display_name, query_count, success_rate, avg_latency, deployment_id) %>% 
  filter(grepl("Uniswap", display_name))
```

Then search for them here: https://arbitrum.graphscan.io/#subgraphs

```{r}
10:30 - V3: 88121   | V2: 65641
12:40 - V3: 308320  | V2: 90232
13:41 - V3: 584292  | V2: 90818
14:15 - V3: 708819  | V2: 91089
15:58 - V3: 1076568 | V2: 92012
20:38 - V3: 2193916 | V2: 94804
23:15 - V3: 2682123 | V2: 96179
```






```{r}
# actively indexing
braindexer_syncing = c("QmQVGK71YBPGhHnrFW2r7soaetv6nWmDY7BLFv2rTePDbN",
                       "QmV1KtTWiHKMM58s7zVt3WPZLxCudJLD54gHEBomzrquSn",
                       "QmRhcudFuQv6Usjt6UtQQkg67rEZcbfWwrj75zcN3xY2SY",
                       "QmXZiV6S13ha6QXq4dmaM3TB4CHcDxBMvGexSNu9Kc28EH",
                       "QmWEnV6povhA9Eq9Y315LsjJg7qwv169r1ZGw9o2uT24eZ",
                       "QmZ9kr5Cjepmdrj5EJnmfsneiJtok7rVpk81KUmZzFzkvp",
                       "QmaiMYSZrhz4zftVgpfHTnHr21RYGp7Haf7hhzG2irQ3bZ",
                       "QmR96s6vPXwFmn66vMZFgqEbc36VPptVE3Vow8Pvxy9Xp8",
                       "QmTbEUPjL5QLEWDUSeJrxdz1P5zwBEDf8vm5SwnJwpZe6V",
                       "QmRC25wNr6wSCKUo2EsJr56MF9ggmPewNqf534T2DiT2xD",
                       "QmcDve6D86Y7VCNkuEduoF43gthRqsw4KaW7MDk4ZjQUp7",
                       "QmVU5ySHH4rtrWsh7ZNJiA6WfnUbX6NSMgdpGenqbJXKMp",
                       "QmYXL6XeXyGC2DCnoQ45ApG68pi8irCZdRdtFx69FetRDd",
                       "QmRtThzzq3zyGLbzVfNEUycjfddfJodLDZZcNQGYr8tNkL",
                       "QmNWuoJm4vdpCqi8uZ3JusWoGbRvDn1HB2RhaLqDyq5Qzp",
                       "QmRJwFemjzSz1iAvepk4FoLqTDLgFKmqegGyn7siz13WqG",
                       "QmXooQwKjSjMePubP3qGQP9JPNhRPr2bB2KWpN9pvrfutz")
# braindexer indexing
braindexing = subgraphs_data %>% 
  arrange(-query_count) %>% 
  filter(deployment_id %in% braindexer_syncing) %>% 
  select(display_name, query_count, success_rate, avg_latency, deployment_id) 
  

# braindexer not indexing
`%notin%` <- Negate(`%in%`)
not_braindexing = subgraphs_data %>% 
  arrange(-query_count) %>% 
  # filtering for 
  filter(deployment_id %notin% braindexer_syncing) %>% 
  select(display_name, query_count, success_rate, avg_latency, deployment_id) 

sum(braindexing$query_count)
sum(subgraphs_data$query_count)
sum(braindexing$query_count)/sum(subgraphs_data$query_count)

not_braindexing
braindexing
```


